### ISSUE TITLE
Unable to stop a (folder) stream

### ISSUE THREAD

**Issue by Milanzor** [vinceau/slp-realtime#68]
Hi,

When using SlpFolderStream+SlpRealtime, I'm unable to cancel/stop watching the folder or streams.

I've setup a bare reproduction repo: https://github.com/Milanzor/example-slp-realtime-not-closing

Mainly want to achieve this for testing, now I've checked the tests in this repo which also do things with SlpRealtime, but that uses RxSlpStream and manually pipes the slp through `pipeFileContents`. 

Perhaps I've overlooked something, in fact, I hope I have.

Thanks!

**Comment by Milanzor** [comment]
I figured out it's the chokidar watcher that stays up. I'll dig to see if there's any way to close it, but it looks like the `watcher` from `src/stream/slpFolderStream.ts:68` is never exposed.

**Comment by vinceau** [comment]
Thanks for looking into this! The folder stream has historically been pretty jank so I'm not surprised if there are bugs with it. It's no longer used in Project Clippi so I also haven't had a need to go back and look into it again.

**Comment by Milanzor** [comment]
Thanks for replying!

I'm new to Typescript but would you merge a PR if I made one? 

Otherwise I could look into the Dolphin and console connection instead for my project.

Thanks.

**Comment by vinceau** [comment]
Yeah of course! If you can identify the bug and PR a fix, I would definitely merge it!
